COLORS = [
    "pink",
    "colorless",
    "reddish brown",
    "purple",
    "brown",
    "red",
    "blue",
    "yellow",
    "green",
    "black",
    "violet",
    "rose",
    "deep blue",
    "sky blue",
    "pale yellow",
    "dark green",
    "red brown",
    "orange",
    "dark red",
    "grey",
    "white",
    "light blue",
    "black brown",
    "pale pink",
    "slightly pink",
    "red-brown",
    "light purple",
    "green yellow",
    "dark brown",
    "primrose yellow",
    "cyan",
    "light green",
    "faint pink",
    "orange brown",
    "dark blue",
    "red/purple",
    "blue green",
    "pale brown",
    "pink/purple",
    "light yellow",
    "pale green",
    "dark turquiose",
    "yellowish white",
    "light brown",
    "pale blue",
    "dark purple",
    "yellow-green",
    "black green",
    "green-yellow",
    "flavescens",
    "light pink",
    "intense violet",
    "aubergine",
    "yellowish yellow",
    "orange red",
    "deep-blue",
    "lilac",
    "pale violet",
    "courless",
    "dark-violet",
    "gold",
    "light red",
    "yellow-orange",
    "amber",
    "pale-yellow",
    "green-black",
    "buff",
    "deep yellow",
    "deep red",
    "whiteish colorless",
    "red-violet",
    "pale red",
    "lavender",
    "straw yellow",
    "yellow green",
    "brown-red",
    "purple black",
    "black purple",
    "turquoise",
    "brown orange",
    "light-purple",
    "greenish blue",
    "light violet",
    "aquamarine",
    "wheat",
    "ruby red",
    "navy blue",
    "deep purple",
    "green blue",
    "plate",
    "gray",
    "red-orange",
    "black-brown",
    "red purple",
    "dark pink",
    "dark purplish-red",
    "purple-red",
    "pink-violet",
    "blackish purple",
    "reddish purple",
    "bright yellow",
    "turquoise blue",
    "black red",
    "orange-red",
    "reddish",
    "greenish-yellow",
    "mauve",
    "orange-yellow",
    "dark violet",
    "red-yellow",
    "yellowish",
    "translucent",
    "magenta",
    "beige",
    "greenish cyan",
    "dark orange",
    "cherry red",
    "deep blue-black",
    "light orange",
    "deep brown",
    "green-blue",
    "dark yellow",
    "crimson",
    "orange yellow",
    "white",
    "claybank",
    "azure",
    "glaucous",
    "greenish green",
    "deep green",
    "violet red",
    "yellow-red",
    "greenish-blue",
    "light colorless",
    "brown yellow",
    "bluish violet",
    "golden yellow",
    "red-black",
    "intense purple",
    "peach",
    "scarlet",
    "dull dark black",
    "violet-red",
    "dark rose",
    "blue violet",
    "amaranthine",
    "jasmine",
    "light-brown",
    "purple-blue",
    "dark-blue",
    "pink-purple",
    "pink-red",
    "light",
    "purple red",
    "brown-yellow",
    "grass green",
    "jonquil",
    "yellowish green",
    "pale straw",
    "pale purple",
    "dark-red",
    "green/brown",
    "green-brown",
]
